# Generated by Django 4.2.7 on 2023-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
